apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      containers:
        - name: validator
          image: gcr.io/cloud-a3-454304/validator-service:latest
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: shared-storage
              mountPath: /kirtan_PV_dir
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: validator-service
spec:
  selector:
    app: validator
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer